global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "energy-api"
    scheme: https
    static_configs:
      - targets: ["predictor-of-energy-market-day-ahead.onrender.com"]
    metrics_path: "/metrics"